image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

environment:
  matrix:
    - db: MySQL

for:
  -
    matrix:
      only:
        - db: MySQL

    install:
      - sudo curl -SL https://github.com/docker/compose/releases/download/v2.7.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
      - sudo chmod +x /usr/local/bin/docker-compose
      - sudo docker-compose -f /home/appveyor/projects/diploma/docker-compose.yml up -d
      - sleep 20
      - java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -jar artifacts/aqa-shop.jar &
      - sleep 20

    build_script:
      - chmod +x gradlew
      - ./gradlew test --info -Dselenide.headless=true -DdbUrl=jdbc:mysql://localhost:3306/app
      - sudo docker-compose down

 
